[package]
name = "fractus-atlas"
version = "1.1.2"
description = "An image viewer which allows you to quickly move them in folders."
authors = ["Jimskapt <rami.programmer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2"
regex = "^1"
web-view = "^0.6"
rand = "^0"
dunce = "^1"
serde = "^1"
serde_derive = "^1"
serde_json = "^1"
trash = "^1"
toml = "^0"
