[package]
name = "fractus-atlas"
version = "1.14.2"
description = "An image viewer which allows you to quickly move them in folders."
homepage = "https://github.com/Jimskapt/fractus-atlas"
repository = "https://github.com/Jimskapt/fractus-atlas"
keywords = ["image", "images", "fast", "browsing", "viewer", "folder", "folders", "sort", "sorting"]
publish = false
authors = ["Jimskapt <rami.programmer@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.17", features = ["env"] }
regex = "1.5.5"
web-view = "0.7.3"
rand = "0.8.5"
dunce = "1.0.2"
serde = "1.0.137"
serde_derive = "1.0.137"
serde_json = "1.0.81"
trash = "2.1.0"
toml = "0.5.9"
tinyfiledialogs = "3.9.1"
tree_magic = "0.2.3"
iron = "0.6.1"
human-panic = "1.0.3"
charlie_buffalo = "1.0.2"
rmp-serde = "1.1.1"
chrono = "0.4.19"
opener = "0.5.0"
multipath = "1.0.0"
